# Generated by Django 4.2.5 on 2023-10-02 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='название аниме')),
                ('description', models.CharField(max_length=300, verbose_name='описание')),
                ('rate', models.FloatField(max_length=5, verbose_name='рейтинг')),
                ('poster', models.ImageField(null=True, upload_to='posters', verbose_name='постер')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/%Y/', verbose_name='видео')),
            ],
            options={
                'verbose_name': 'аниме',
                'verbose_name_plural': 'аниме',
                'ordering': ('-rate',),
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=130, unique=True, verbose_name='название жанра')),
            ],
            options={
                'verbose_name': 'жанр',
                'verbose_name_plural': 'жанры',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='VideoFileType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='название')),
            ],
            options={
                'verbose_name': 'тип расширения видео-файла',
                'verbose_name_plural': 'типы расширений видео-файлов',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=254, verbose_name='текст')),
                ('anime', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anime_comments', to='anime.anime', verbose_name='аниме')),
            ],
            options={
                'verbose_name': 'комментарий',
                'verbose_name_plural': 'комментарии',
                'ordering': ('-id',),
            },
        ),
    ]
