# Generated by Django 4.2.5 on 2023-10-12 06:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episode',
            options={'ordering': ('-id',), 'verbose_name': 'серии', 'verbose_name_plural': 'серии'},
        ),
        migrations.AlterField(
            model_name='anime',
            name='poster',
            field=models.ImageField(blank=True, default='/media/default/poster.jpg', upload_to='posters', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'gif'], message='Sorry, this file format is not supported')], verbose_name='постер'),
        ),
    ]
